# Define the mapping between sites and Public Health Regions;
  phr_mapping <- c(
    "Thunder Bay - Atlantic Ave." = "North West", 
    "Dryden" = "North West", 
    "Kenora" = "North West",
    
    
    "Greater Sudbury" = "North East", 
    "Haileybury" = "North East", 
    "Kapuskasing" = "North East",
    "Kirkland Lake" = "North East",
    "Mattagami River" = "North East",
    "Moosonee" = "North East",
    "North Bay" = "North East",
    "Sault St. Marie" = "North East",
   
    
    "Belleville" = "East",
    "Brockville" = "East", 
    "Durham - Liverpool" = "East",
    "Kemptville" = "East",
    "Pembroke" = "East",
    "Petawawa" = "East", 
    "Penetanguishene" = "East", 
    "Ottawa - ROPEC" = "East",
    "Smiths Falls" = "East",
   
    
    "Minden" = "Central East", 
    "Etobicoke - Humber" = "Central East", 
    "Barrie" = "Central East",
    "Cobourg" = "Central East", "
    Collingwood" = "Central East", 
    "Midland" = "Central East",
    "Durham - Ajax/Bayly" = "Central East", 
    "Clarkson" = "Central East", 
    "Port Darlington" = "Central East",
    "Havelock" = "Central East", 
    "Lakefield" = "Central East",
    "Courtice" = "Central East",
    "Millbrook" = "Central East",
    "Lindsay" = "Central East", 
    "Harmony Creek" = "Central East",
    "Norwood" = "Central East", 
    "Newcastle" = "Central East", 
    "Peterborough" = "Central East",
    "Orillia" = "Central East", 
    "Corbett Creek" = "Central East",
    "Cambridge - Galt" = "Central East",
    "York - Humber AMF" = "Central East", 
    "Waterloo" = "Central East",
    
    
    "Ashbridges Bay" = "Toronto", 
    "Highland Creek" = "Toronto", 
    "Cornwall" = "Toronto",
    "North Toronto" = "Toronto",
   
    
    "London - Adelaide" = "South West", 
    "Amherstburg" = "South West", 
    "Chatham" = "South West",
    "Craigleith" = "South West",
    "Windsor - Denis St. Pierre" = "South West", 
    "Goderich" = "South West",
    "London - Greenway" = "South West",
    "Leamington" = "South West", 
    "Windsor - Little River" = "South West",
    "Windsor - Lou Romano" = "South West",
    "Owen Sound" = "South West", 
    "London - Oxford" = "South West",
    "London - Pottersburg" = "South West", 
    "Sarnia" = "South West", 
    "St. Thomas" = "South West",
    "Stratford" = "South West", 
    "London - Vauxhaul" = "South West", 
    "Ravensview" = "South West",
    "Woodstock" = "South West",
    
    
    "Acton" = "Central West", 
    "Fort Erie - Anger Ave." = "Central West", 
    "Niagara - Baker Road" = "Central West",
    "Brantford" = "Central West",
    "Caledonia" = "Central West", 
    "Crystal Beach" = "Central West",
    "Wallaceburg" = "Central West", 
    "Georgetown" = "Central West", 
    "Guelph" = "Central West",
    "Hagersville" = "Central West",
    "Hamilton - Woodward" = "Central West",
    "Mississauga - GE Booth" = "Central West", 
    "Mid-Halton" = "Central West",
    "Oakville - SE" = "Central West",
    "Oakville - SW" = "Central West",
    "Orangeville" = "Central West", 
    "Port Weller" = "Central West", 
    "Queenston" = "Central West",
    "Simcoe" = "Central West", 
    "Niagara - Stamford" = "Central West", 
    "Kitchener" = "Central West",
    "Welland" = "Central West"
    )
